### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ionutz** [skeeks-semenov/yii2-assets-auto-compress#5]
GET http://localhost/advv/ net::ERR_CONNECTION_REFUSED

**Comment by skeeks-semenov** [comment]
Yes, now it works only real projects. Not local. Because the contents of each Asset file obtained by the following function.

https://github.com/skeeks-semenov/yii2-assets-auto-compress/blob/master/AssetsAutoCompressComponent.php#L498

Perhaps in the future, it can be modified. But basically this thing and should be used only in real-life projects.

**Comment by ionutz** [comment]
thanks, it works real project but I have  an error 
use Leaflet map

**Comment by skeeks-semenov** [comment]
Fixed: https://github.com/skeeks-semenov/yii2-assets-auto-compress/releases/tag/1.3.1.1
